sudo: required
language: java
script:
- mvn test
notifications:
  slack:
    secure: KjG5Si0gSeu6/8LP/IzRPvmoir9z7V1puVGd5Krx5jJ1gqo1gTzPxXDAZpQrbI8GCYT1ChIVVI/6hJ27yhl4TVdBWZr8PJgxOx8ZvXgw5GjRkJgYqbJjPBmJEfmKnVsEIM2tGAEDwnCUHYcqGtmAu8qKfPzW1b30DYoOQHN0E6vofa3YBJVSjRRQCyy1n/6dk77dwQvRgvbeSCYY54nnn4rXmanfkltG6qUS5+XrQD61lFDA78eNBrBFIvrMPjqGlrWyCJ84C6zqSBMOU3dqxHQpM6O5n2kzO1JTWUTQlyA0cxI6DiN3ita5WuXbZ6IYsVOCRdJZtGIMokIZ4Ex2Lg8GIBynV153EEZX0O+dtkPs+H6b0BycAxuDMw6SMgtkRw2B5VPyobTv54Pu/jwcx/2IeE0PS83w7FONcP7EZD3zRt3W0FmXYTSNLKPfq6xDd3tmW/ucTqOX45pkob5zigM+eOWtOhdCGlc+xdluCB70kqfeCgzTbW+ETQ2rq4Q5dN9xPtWGU3gEjbw+SOp3J/AD3cpCDOiJpVK5mZxHreZKzw4vL4tcy3b1a0+tqQKdSFbcmmI/onci4jsBhikhTZpzX3M7uqoznN0GsIjYiiUlcE2ODOJkGw3Cobe/JMf5u/AmHUjPnfnhe49j0iLVGNE0oz7wZuWQELRzvnfdMag=
