/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ch.hsr.markovshield;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ClickStream extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ClickStream\",\"namespace\":\"ch.hsr.markovshield\",\"fields\":[{\"name\":\"session\",\"type\":\"string\"},{\"name\":\"user\",\"type\":\"string\"},{\"name\":\"clicks\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Click\",\"fields\":[{\"name\":\"session\",\"type\":\"string\"},{\"name\":\"url\",\"type\":\"string\"}]}}}]}");
    private static final long serialVersionUID = 397704532979096390L;
    private static final org.apache.avro.io.DatumWriter
            WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);
    private static final org.apache.avro.io.DatumReader
            READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);
    @Deprecated
    public java.lang.CharSequence session;
    @Deprecated
    public java.lang.CharSequence user;
    @Deprecated
    public java.util.List<Click> clicks;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public ClickStream() {
    }

    /**
     * All-args constructor.
     * @param session The new value for session
     * @param user The new value for user
     * @param clicks The new value for clicks
     */
    public ClickStream(java.lang.CharSequence session, java.lang.CharSequence user, java.util.List<Click> clicks) {
        this.session = session;
        this.user = user;
        this.clicks = clicks;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Creates a new ClickStream RecordBuilder.
     * @return A new ClickStream RecordBuilder
     */
    public static ClickStream.Builder newBuilder() {
        return new ClickStream.Builder();
    }

    /**
     * Creates a new ClickStream RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new ClickStream RecordBuilder
     */
    public static ClickStream.Builder newBuilder(ClickStream.Builder other) {
        return new ClickStream.Builder(other);
    }

    /**
     * Creates a new ClickStream RecordBuilder by copying an existing ClickStream instance.
     * @param other The existing instance to copy.
     * @return A new ClickStream RecordBuilder
     */
    public static ClickStream.Builder newBuilder(ClickStream other) {
        return new ClickStream.Builder(other);
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return session;
            case 1:
                return user;
            case 2:
                return clicks;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                session = (java.lang.CharSequence) value$;
                break;
            case 1:
                user = (java.lang.CharSequence) value$;
                break;
            case 2:
                clicks = (java.util.List<Click>) value$;
                break;
            default:
                throw new org.apache.avro.AvroRuntimeException("Bad index");
        }
    }

    /**
     * Gets the value of the 'session' field.
     * @return The value of the 'session' field.
     */
    public java.lang.CharSequence getSession() {
        return session;
    }

    /**
     * Sets the value of the 'session' field.
     * @param value the value to set.
     */
    public void setSession(java.lang.CharSequence value) {
        this.session = value;
    }

    /**
     * Gets the value of the 'user' field.
     * @return The value of the 'user' field.
     */
    public java.lang.CharSequence getUser() {
        return user;
    }

    /**
     * Sets the value of the 'user' field.
     * @param value the value to set.
     */
    public void setUser(java.lang.CharSequence value) {
        this.user = value;
    }

    /**
     * Gets the value of the 'clicks' field.
     * @return The value of the 'clicks' field.
     */
    public java.util.List<Click> getClicks() {
        return clicks;
    }

    /**
     * Sets the value of the 'clicks' field.
     * @param value the value to set.
     */
    public void setClicks(java.util.List<Click> value) {
        this.clicks = value;
    }

    /**
     * RecordBuilder for ClickStream instances.
     */
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ClickStream>
            implements org.apache.avro.data.RecordBuilder<ClickStream> {

        private java.lang.CharSequence session;
        private java.lang.CharSequence user;
        private java.util.List<Click> clicks;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(ClickStream.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.session)) {
                this.session = data().deepCopy(fields()[0].schema(), other.session);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.user)) {
                this.user = data().deepCopy(fields()[1].schema(), other.user);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.clicks)) {
                this.clicks = data().deepCopy(fields()[2].schema(), other.clicks);
                fieldSetFlags()[2] = true;
            }
        }

        /**
         * Creates a Builder by copying an existing ClickStream instance
         * @param other The existing instance to copy.
         */
        private Builder(ClickStream other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.session)) {
                this.session = data().deepCopy(fields()[0].schema(), other.session);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.user)) {
                this.user = data().deepCopy(fields()[1].schema(), other.user);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.clicks)) {
                this.clicks = data().deepCopy(fields()[2].schema(), other.clicks);
                fieldSetFlags()[2] = true;
            }
        }

        /**
         * Gets the value of the 'session' field.
         * @return The value.
         */
        public java.lang.CharSequence getSession() {
            return session;
        }

        /**
         * Sets the value of the 'session' field.
         * @param value The value of 'session'.
         * @return This builder.
         */
        public ClickStream.Builder setSession(java.lang.CharSequence value) {
            validate(fields()[0], value);
            this.session = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'session' field has been set.
         * @return True if the 'session' field has been set, false otherwise.
         */
        public boolean hasSession() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'session' field.
         * @return This builder.
         */
        public ClickStream.Builder clearSession() {
            session = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'user' field.
         * @return The value.
         */
        public java.lang.CharSequence getUser() {
            return user;
        }

        /**
         * Sets the value of the 'user' field.
         * @param value The value of 'user'.
         * @return This builder.
         */
        public ClickStream.Builder setUser(java.lang.CharSequence value) {
            validate(fields()[1], value);
            this.user = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'user' field has been set.
         * @return True if the 'user' field has been set, false otherwise.
         */
        public boolean hasUser() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'user' field.
         * @return This builder.
         */
        public ClickStream.Builder clearUser() {
            user = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'clicks' field.
         * @return The value.
         */
        public java.util.List<Click> getClicks() {
            return clicks;
        }

        /**
         * Sets the value of the 'clicks' field.
         * @param value The value of 'clicks'.
         * @return This builder.
         */
        public ClickStream.Builder setClicks(java.util.List<Click> value) {
            validate(fields()[2], value);
            this.clicks = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'clicks' field has been set.
         * @return True if the 'clicks' field has been set, false otherwise.
         */
        public boolean hasClicks() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'clicks' field.
         * @return This builder.
         */
        public ClickStream.Builder clearClicks() {
            clicks = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        @Override
        public ClickStream build() {
            try {
                ClickStream record = new ClickStream();
                record.session = fieldSetFlags()[0] ? this.session : (java.lang.CharSequence) defaultValue(fields()[0]);
                record.user = fieldSetFlags()[1] ? this.user : (java.lang.CharSequence) defaultValue(fields()[1]);
                record.clicks = fieldSetFlags()[2] ? this.clicks : (java.util.List<Click>) defaultValue(fields()[2]);
                return record;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }


}
